urls:
  - url: https://can019.github.io/spring-base/release/openapi3.yaml
    name: "API 1"
  - url: https://can019.github.io/spring-base/release/openapi3.yaml
    name: "API 2"
  - url: https://can019.github.io/spring-base/release/openapi3.yaml
    name: "API 3"
validatorUrl: null
docExpansion: none
apisSorter: alpha
operationsSorter: alpha
