name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '💥 Migragion'
    labels:
      - '💥 migragion'
  - title: '🚀 Features'
    labels:
      - '✨ New Feature'
  - title: '🐛 Bug Fixes'
    labels:
      - '🐛 Fix bug'
  - title: '♻️ Refactor'
    labels:
      - '♻️ Refactor'
      - '⚡ Performance'
  - title: '🛠️ Development set up'
    labels:
      - '🛠️ Develop setting'
      - '📝 Documentation'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes
  $CHANGES
