openapi: 3.0.1
info:
  title: SPRING-BASE
  description: Spring base
  version: 0.2.1
servers:
- url: http://localhost:8080
tags: []
paths:
  /api/v0/hello:
    get:
      tags:
      - api
      summary: "[Get] hello"
      description: "[Get] hello"
      operationId: hello
      responses:
        "200":
          description: "200"
          content:
            text/plain;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/api-v0-hello486549215'
              examples:
                hello:
                  value: hello
components:
  schemas:
    api-v0-hello486549215:
      type: object
