name: "Set up gh page resource"
on:
  pull_request:
    types: [closed]
    branches:
      - main
      - develop
  release:
    types: [created]

jobs:
  develop:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get commit ID
        id: get_commit_id
        run: echo "::set-output name=commit_id::$(git rev-parse HEAD)"

      - name: Set environment variable
        run: echo "COMMIT_ID=${{ steps.get_commit_id.outputs.commit_id }}" >> $GITHUB_ENV

      - name: Save scripts, config
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: |
            .github/config/gh-pages.yml
            .github/scripts

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'gh-pages'

      - name: Configure Git # commit을 위한 git config 설정
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Set python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install python3 dependencies
        run: pip3 install pyyaml

      - name: Download integrationTest test reports
        uses: actions/download-artifact@v3
        with:
          name: docs
          path: .github

      - name: ls
        run: ls -R

      - name: Generate develop docs resource
        run: python3 .github/scripts/link_docs.py -i $COMMIT_ID -t develop

      - name: Commit to gh-pages
        run: |
          git add docs/ -f
          git status
          git commit -m "docs: Init docs linking $COMMIT_ID"

      - name: Push changes to gh-pages branch
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}

  release:
    if: github.event.action == 'created
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Get commit ID
        id: get_commit_id
        run: echo "::set-output name=commit_id::$(git rev-parse HEAD)"

      - name: Get release version
        id: get_release_version
        run: echo "::set-output name=release_version::${{ github.event.release.tag_name }}"

      - name: Set environment variable
        run: |
          echo "COMMIT_ID=${{ steps.get_commit_id.outputs.commit_id }}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${{ steps.get_release_version.outputs.release_version }}" >> $GITHUB_ENV

      - name: Save scripts, config
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: |
            .github/config/gh-pages.yml
            .github/scripts

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'gh-pages'

      - name: Configure Git # commit을 위한 git config 설정
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Set python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install python3 dependencies
        run: pip3 install pyyaml

      - name: Download integrationTest test reports
        uses: actions/download-artifact@v3
        with:
          name: docs
          path: .github

      - name: ls
        run: ls -R

      - name: Init docs linking and commit
        run: |
          git add docs/ -f
          git status
          git commit -m "docs: Init docs linking $COMMIT_ID"

      - name: Copy develop report to release and commit
        run: |
          git mv docs/develop/$COMMIT_ID/ docs/release/$RELEASE_VERSION/
          
          git add docs/release/$RELEASE_VERSION
          git commit -m "chore: Turn $COMMIT_ID into Release $RELEASE_VERSION"

      - name: Generate develop docs resource
        run: python3 .github/scripts/link_docs.py -i $COMMIT_ID -t release

      - name: Push changes to gh-pages branch
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}